name: Github CICD for Notejam

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checkout-SCM:
    runs-on: self-hosted
    steps:
    - name: checkout SCM
      uses: actions/checkout@v2
      
  build-docker-image:
    needs: checkout-SCM
    runs-on: self-hosted
    steps:
      - name: Build the docker Image
        run: docker build -t notejam:master .
      - name: Tag the Dcker Image
        run: docker tag notejam:master arkdocr/jenkins:latest

  push-docker-image:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: Login to Dockerhub
        run: docker login -u "${{ secrets.CI_REGISTRY_USER }}" -p "${{ secrets.CI_REGISTRY_PASSWORD }}" ${{ secrets.CI_REGISTRY }}   
      - name: Push the Image to Dockerhub
        run: docker push arkdocr/jenkins:latest

  Deploy-to-GKE:
    needs: push-docker-image
    runs-on: GKE-runner
    env:
        PROJECT_ID: project-k8-326109
        GKE_CLUSTER: cluster-1    
        GKE_ZONE: asia-south2-b 
        credentials: ${{ secrets.GKE_SA_KEY }}
    
    steps:
    - name: Deploy the mysql container
      run: kubectl apply -f ./notejam-kube/mysql-deploy.yaml 
    - name: Deploy the notejam container
      run: kubectl apply -f ./notejam-kube/notejam-deploy.yaml
      